name: release
on:
  push:
#    branches:
#      - test-rel
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-release:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-gnux32
          - x86_64-apple-darwin
          - aarch64-unknown-linux-gnu
          - aarch64-apple-darwin
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt,clippy
      - name: Install Targets
        shell: bash
        run: |
          sudo apt install gcc-multilib xz-utils liblz4-tool musl-tools asciidoctor zsh brotli zstd build-essential
          rustup target add ${{ matrix.target }}
      - name: Build
        shell: bash
        run: |
          cargo build --release --target ${{ matrix.target }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/${{ matrix.target }}/release/surrogate